# =============================================================
#  Projet IDH Afrique — Inventaire Ansible
#  Étudiant : Frank Laurel | ID : 300143951
# =============================================================
#
#  ⚠️  AVANT D'UTILISER : remplacer l'IP par celle de votre VM
#  Pour connaître l'IP de votre VM Ubuntu :
#    ip addr show eth0   (sur la VM)
#    hostname -I         (sur la VM)
#
#  Exemple : 192.168.1.105

[vm_ubuntu]
idh-vm ansible_host=10.7.237.206 ansible_user=ubuntu 

[vm_ubuntu:vars]
ansible_python_interpreter=/usr/bin/python3
project_dir=/home/ubuntu/300143951
