---
- name: Installer et configurer nginx
  hosts: web
  become: yes

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

  tasks:

    - name: Installer nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copier la page HTML
      copy:
        src: files/index.html
        dest: /var/www/html/index.nginx-debian.html
      notify: restart nginx

    - name: Démarrer nginx et activer au démarrage
      service:
        name: nginx
        state: started
        enabled: yes
